---
title: "Final Project - STAT 508"
author: "Joseph Abraham, Pallavi Surana, Xue Zhang"
date: "5/3/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir='/Users/josephabraham/Documents/THE LAST SEMESTER/STAT 581/restatisticalconsultingm_a_s_capstone/')
```

# Intro



# Data

```{r}
covid=read.csv("/Users/josephabraham/Documents/THE LAST SEMESTER/STAT 508/Final Project/novel-corona-virus-2019-dataset/COVID19_line_list_data.csv",header = TRUE)
covid
```

```{r}
no_age=is.na(covid$age)
covid_age=covid[-no_age,]
death_var=rep(1,length(covid_age$id))
death_var[covid_age$death=="0"]=0
plot(covid_age$age,death_var)
age.model=glm(death_var~age+gender,family=poisson(link="log"),data=covid_age)
summary(age.model)
```

```{r}
no_gender=is.na(covid$gender)
covid_gender=covid[-no_gender,]
death_var=rep(1,length(covid_gender$id))
death_var[covid_gender$death=="0"]=0
table(covid_gender$gender,death_var)
gender.model=glm(death_var~gender,family=poisson(link="log"),data=covid_gender)
summary(gender.model)
```



# Analysis

# Conclusion